<?xml version="1.0" encoding="UTF-8"?>
<!-- 
****
****     Filename : marc21_auth_validate.xsl
****       Author : Kosmas Giannis <kosmasgiannis@gmail.com>
**** Generated by : marc21auth2xsl.php
****         Note : This file is autogenerated
****
-->
<xsl:stylesheet xmlns:marc="http://www.loc.gov/MARC21/slim" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:xs="http://www.w3.org/2001/XMLSchema" exclude-result-prefixes="marc xs" version="1.0">
  <xsl:output indent="yes" encoding="UTF-8"/>
  <xsl:template name="validateDatafield">
    <xsl:param name="isObselete" select="false()"/>
    <xsl:param name="sCodesNR"/>
    <xsl:param name="sCodesR"/>
    <xsl:param name="i1Values"/>
    <xsl:param name="i2Values"/>
    <xsl:if test="$isObselete=true()">
      <warning type="ObsoleteTag">
        <xsl:call-template name="controlNumber"/>
        <tag>
          <xsl:value-of select="@tag"/>
        </tag>
      </warning>
    </xsl:if>
    <xsl:call-template name="checkNRSubfields">
      <xsl:with-param name="sCodesNR" select="$sCodesNR"/>
    </xsl:call-template>
    <xsl:call-template name="validateSubfields">
      <xsl:with-param name="sCodes" select="concat($sCodesR,$sCodesNR)"/>
    </xsl:call-template>
    <xsl:call-template name="validateIndicator1">
      <xsl:with-param name="iValues" select="$i1Values"/>
    </xsl:call-template>
    <xsl:call-template name="validateIndicator2">
      <xsl:with-param name="iValues" select="$i2Values"/>
    </xsl:call-template>
  </xsl:template>
  <xsl:template name="checkNRSubfields">
    <xsl:param name="sCodesNR"/>
    <xsl:if test="$sCodesNR">
      <xsl:if test="count(marc:subfield[@code=substring($sCodesNR,1,1)])&gt;1">
        <error type="NonRepeatableSubField">
          <xsl:call-template name="controlNumber"/>
          <tag>
            <xsl:value-of select="@tag"/>
          </tag>
          <code>
            <xsl:value-of select="substring($sCodesNR,1,1)"/>
          </code>
        </error>
      </xsl:if>
      <xsl:call-template name="checkNRSubfields">
        <xsl:with-param name="sCodesNR" select="substring($sCodesNR,2)"/>
      </xsl:call-template>
    </xsl:if>
  </xsl:template>
  <xsl:template name="validateSubfields">
    <xsl:param name="sCodes"/>
    <xsl:for-each select="marc:subfield">
      <xsl:if test="not(contains($sCodes, @code))">
        <error type="InvalidSubfieldCode">
          <xsl:call-template name="controlNumber"/>
          <tag>
            <xsl:value-of select="../@tag"/>
          </tag>
          <code>
            <xsl:value-of select="@code"/>
          </code>
        </error>
      </xsl:if>
    </xsl:for-each>
  </xsl:template>
  <xsl:template name="validateIndicator1">
    <xsl:param name="iValues"/>
    <xsl:if test="not(contains($iValues,@ind1))">
      <error type="InvalidIndicator">
        <xsl:call-template name="controlNumber"/>
        <tag>
          <xsl:value-of select="@tag"/>
        </tag>
        <ind1>
          <xsl:value-of select="@ind1"/>
        </ind1>
      </error>
    </xsl:if>
  </xsl:template>
  <xsl:template name="validateIndicator2">
    <xsl:param name="iValues"/>
    <xsl:if test="not(contains($iValues,@ind2))">
      <error type="InvalidIndicator">
        <xsl:call-template name="controlNumber"/>
        <tag>
          <xsl:value-of select="@tag"/>
        </tag>
        <ind2>
          <xsl:value-of select="@ind2"/>
        </ind2>
      </error>
    </xsl:if>
  </xsl:template>

  <xsl:template match="/">
    <validationReport>
      <xsl:if test="marc:collection">
        <xsl:apply-templates select="marc:collection/marc:record"/>
      </xsl:if>
      <xsl:if test="marc:record">
        <xsl:apply-templates select="marc:record"/>
      </xsl:if>
    </validationReport>
  </xsl:template>

  <xsl:template match="marc:record">
    <xsl:if test="count(marc:datafield[starts-with(@tag,'1')]) &gt; 1">
      <error type="TooManyMainHeadings"/>
    </xsl:if>
    <xsl:if test="count(marc:datafield[starts-with(@tag,'1')]) = 0">
      <error type="NoMainHeading"/>
    </xsl:if>
    <xsl:if test="count(marc:controlfield[@tag=001]) != 1">
<!--
      <error type="MandatoryNonRepeatable">
        <tag>001</tag>
      </error>
-->
      <warning type="MandatoryTag">
        <tag>001</tag>
      </warning>
    </xsl:if>
    <xsl:if test="count(marc:controlfield[@tag=003]) &gt; 1">
      <error type="NonRepeatable">
        <tag>003</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:controlfield[@tag=005]) &gt; 1">
      <error type="NonRepeatable">
        <tag>005</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:controlfield[@tag=008]) != 1">
      <error type="MandatoryNonRepeatable">
        <tag>008</tag>
      </error>
    </xsl:if>
<!-- -->

    <xsl:if test="count(marc:datafield[@tag=010])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>010</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=040])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>040</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=042])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>042</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=043])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>043</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=045])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>045</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=066])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>066</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=073])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>073</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=100])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>100</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=110])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>110</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=111])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>111</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=130])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>130</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=148])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>148</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=150])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>150</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=151])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>151</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=155])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>155</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=162])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>162</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=180])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>180</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=181])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>181</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=182])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>182</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=185])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>185</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=378])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>378</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=663])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>663</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=664])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>664</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=665])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>665</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=666])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>666</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=675])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>675</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=682])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>682</tag>
      </error>
    </xsl:if>
    <xsl:if test="count(marc:datafield[@tag=788])&gt;1">
      <error type="NonRepeatable">
        <xsl:call-template name="controlNumber"/>
        <tag>788</tag>
      </error>
    </xsl:if>

<!-- -->
    <xsl:apply-templates select="marc:datafield"/>
    <xsl:apply-templates select="marc:controlfield"/>
  </xsl:template>
  <xsl:template match="marc:controlfield[@tag=001]">
  </xsl:template>
  <xsl:template match="marc:controlfield[@tag=003]">
  </xsl:template>
  <xsl:template match="marc:controlfield[@tag=005]">
  </xsl:template>
  <xsl:template match="marc:controlfield[@tag=008]">
  </xsl:template>
<!-- -->

  <xsl:template match="marc:datafield[@tag=010]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">z8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=014]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=016]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">z8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a2</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 7</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=020]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">qz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">ac6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=022]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">myz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">al6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=024]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">qz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">acd26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">78</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=031]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">dqstuyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">abcegmnopr26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=034]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">st08</xsl:with-param>
      <xsl:with-param name="sCodesNR">defgjkmnprxyz236</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 01</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=035]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">z8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=040]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">de8</xsl:with-param>
      <xsl:with-param name="sCodesNR">abcf6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=042]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">a</xsl:with-param>
      <xsl:with-param name="sCodesNR"></xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=043]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abc028</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=045]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abc8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=046]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">uv8</xsl:with-param>
      <xsl:with-param name="sCodesNR">fgklopst26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=050]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=052]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">bd8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 17</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=053]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abc6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=055]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=060]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=065]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abc26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=066]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">c</xsl:with-param>
      <xsl:with-param name="sCodesNR">ab</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=070]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=072]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">x8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 07</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=073]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">a8</xsl:with-param>
      <xsl:with-param name="sCodesNR">z6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=080]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">x8</xsl:with-param>
      <xsl:with-param name="sCodesNR">ab26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 01</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=082]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">017</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=083]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">y58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abcz26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">017</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">04</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=086]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">z58</xsl:with-param>
      <xsl:with-param name="sCodesNR">ad26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 01</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=087]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">abc26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 01</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=100]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">cejkmnpvxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">abdfghloqrst6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">013</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=110]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">bdekmnpvxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">acfghlorst6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=111]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ejknpvxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">acdfghlqst6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=130]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">dkmnpvxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">afghlorst6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">0123456789</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=148]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=150]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">ab6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=151]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=155]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=162]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=180]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=181]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=182]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=185]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=260]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai08</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=336]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ab8</xsl:with-param>
      <xsl:with-param name="sCodesNR">236</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=360]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai08</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=368]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abc08</xsl:with-param>
      <xsl:with-param name="sCodesNR">26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=370]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">cefguv08</xsl:with-param>
      <xsl:with-param name="sCodesNR">abst26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=371]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">amuvz48</xsl:with-param>
      <xsl:with-param name="sCodesNR">bcdest6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=372]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">auv08</xsl:with-param>
      <xsl:with-param name="sCodesNR">st26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=373]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">auv08</xsl:with-param>
      <xsl:with-param name="sCodesNR">st26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=374]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">auv08</xsl:with-param>
      <xsl:with-param name="sCodesNR">st26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=375]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">auv8</xsl:with-param>
      <xsl:with-param name="sCodesNR">st26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=376]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abcuv08</xsl:with-param>
      <xsl:with-param name="sCodesNR">st26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=377]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">al8</xsl:with-param>
      <xsl:with-param name="sCodesNR">26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 7</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=378]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">uv8</xsl:with-param>
      <xsl:with-param name="sCodesNR">q6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=385]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ar08</xsl:with-param>
      <xsl:with-param name="sCodesNR">mn236</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=386]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ar08</xsl:with-param>
      <xsl:with-param name="sCodesNR">mn236</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=400]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ceijkmnpvxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">abdfghloqrstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">013</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=410]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">bdeikmnpvxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">acfghlorstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=411]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">eijknpvxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">acdfghlqstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=430]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">dikmnpvxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">afghlorstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">0123456789</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=448]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=450]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">abw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=451]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=455]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=462]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">i458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=480]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=481]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=482]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=485]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=500]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ceijkmnpvxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">abdfghloqrstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">013</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=510]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">bdeikmnpvxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">acfghlorstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=511]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">eijknpvxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">acdfghlqstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=530]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">dikmnpvxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">afghlorstw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">0123456789</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=548]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=550]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">abw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=551]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=555]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=562]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">i0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=580]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=581]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=582]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=585]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ivxyz0458</xsl:with-param>
      <xsl:with-param name="sCodesNR">w6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=640]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">az6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">01</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=641]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">8</xsl:with-param>
      <xsl:with-param name="sCodesNR">az6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=642]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">ad6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=643]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ab8</xsl:with-param>
      <xsl:with-param name="sCodesNR">d6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=644]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">abd6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=645]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">ad6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=646]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">ad6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=663]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abt8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=664]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abt8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=665]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">a8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=666]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">a8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=667]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=670]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">u8</xsl:with-param>
      <xsl:with-param name="sCodesNR">ab6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=672]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">w08</xsl:with-param>
      <xsl:with-param name="sCodesNR">abf6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">0123456789</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=673]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">w08</xsl:with-param>
      <xsl:with-param name="sCodesNR">abf6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">0123456789</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=675]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">a8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=678]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">au8</xsl:with-param>
      <xsl:with-param name="sCodesNR">b6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 01</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=680]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai58</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=681]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai8</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=682]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai08</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=688]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">58</xsl:with-param>
      <xsl:with-param name="sCodesNR">a6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> </xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=700]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">cejkmnpvxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">abdfghloqrstw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">013</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=710]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">bdekmnpvxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">acfghlorstw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=711]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ejknpvxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">acdfghlqstw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve">012</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=730]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">dkmnpvxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">afghlorstw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=748]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=750]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">abw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=751]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=755]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=762]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">058</xsl:with-param>
      <xsl:with-param name="sCodesNR">aw26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=780]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">w26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=781]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">w26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=782]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">w26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=785]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">vxyz058</xsl:with-param>
      <xsl:with-param name="sCodesNR">w26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=788]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">ai58</xsl:with-param>
      <xsl:with-param name="sCodesNR">26</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> </xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve">01234567</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=856]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abcdfimstuvwxyz8</xsl:with-param>
      <xsl:with-param name="sCodesNR">hjklnopqr236</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 012347</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 0128</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
  <xsl:template match="marc:datafield[@tag=880]">
    <xsl:call-template name="validateDatafield">
      <xsl:with-param name="sCodesR">abcdefghijklmnopqrstuvwxyz012345789</xsl:with-param>
      <xsl:with-param name="sCodesNR">6</xsl:with-param>
      <xsl:with-param name="i1Values" xml:space="preserve"> 1234567890</xsl:with-param>
      <xsl:with-param name="i2Values" xml:space="preserve"> 1234567890</xsl:with-param>
    </xsl:call-template>
  </xsl:template>
<!-- -->
  <xsl:template match="marc:datafield[starts-with(@tag,'09')]">
  </xsl:template>
  <xsl:template match="marc:datafield[starts-with(@tag,'9')]">
  </xsl:template>

  <xsl:template match="marc:datafield">
    <warning type="UnknownTag">
      <xsl:call-template name="controlNumber"/>
      <tag>
        <xsl:value-of select="@tag"/>
      </tag>
    </warning>
  </xsl:template>
  <xsl:template name="controlNumber">
    <xsl:if test="../marc:controlfield[@tag=001]">
      <xsl:attribute name="controlNumber">
        <xsl:value-of select="../marc:controlfield[@tag=001]"/>
      </xsl:attribute>
    </xsl:if>
  </xsl:template>
</xsl:stylesheet>
